### ISSUE TITLE
A matlab script aims to simplify reading mask generated by subsampling.exe

### ISSUE THREAD

**Issue by siatjiasen** [thomaskuestner/CS_MoCo_LAB#11]
This matlab script call the subsampling.exe in MATLAB via system call, and read generated mask in  subsamplingpatter.txt to MATLAB. Also, the Point Spread Function of ESPReSSo mask is displayed. 
Note: the PSF calculation may be different from the one used by the authors of ESPReSSo. I could not reproduce the PSF in Fig.2 in the paper of ESPReSSo. 

Just rename the upload .txt file to .m file.
[ESPReSSomask_in_matlab.txt](https://github.com/thomaskuestner/CS_LAB/files/653792/ESPReSSomask_in_matlab.txt)

**Comment by thomaskuestner** [comment]
In order to reproduce the results from the ESPReSSo TMI paper, you almost got it right ;-)

There were some minor issues in your script (see attached; rename *.txt to *.m):
1. You should specify a "pf_factor=0.5" to get an ESPReSSo mask 
2. As implemented in the CS_LAB_GUI, the psf is simply retrieved by: psf = abs(fftshift(ifft2(ifftshift(mask))));
(for displaying adjust the scale range accordingly - see attached file)

Hope this helps!

[ESPReSSomask_in_matlab.txt](https://github.com/thomaskuestner/CS_LAB/files/654121/ESPReSSomask_in_matlab.txt)
