### ISSUE TITLE
IceGadgetron VB20P

### ISSUE THREAD

**Issue by moonchgm** [thomaskuestner/CS_MoCo_LAB#15]
Hello,

I try to install CS_LAB package on mMR scanner with IDEA VB20P.  I download "IceGadgetron" for VB17 from IDEA community website, and fixed some lines to compile but all failed. I wonder if k-Space Astronauts group has a working version of IceGadget source code on VB20P. Could you share? Many thanks.

Chan

**Comment by martinschwartz** [comment]
Dear Chan,

please find attached a version of IceGadgetron for VB20P. 

Unfortunately, it might be possible that some code changes have to be done by yourself before running it with the newest CS_LAB sequence package due to different software versions.


If you have any questions regarding installation/compilation, don't hesitate to contact me.


Best regards,
Martin Schwartz

																		   
Martin Schwartz, M. Sc.
University of Tübingen
Section on Experimental Radiology
Fon.: +497071/29-80495



>>> moonchgm <notifications@github.com> 20.09.2017 01:02 >>>
Hello,
I try to install CS_LAB package on mMR scanner with IDEA VB20P. I download "IceGadgetron" for VB17 from IDEA community website, and fixed some lines to compile but all failed. I wonder if k-Space Astronauts group has a working version of IceGadget source code on VB20P. Could you share? Many thanks.
Chan
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
( https://github.com/thomaskuestner/CS_MoCo_LAB/issues/15) , or mute the thread

**Comment by thomaskuestner** [comment]
Compiled libraries (VB20P) were added with afd1cc5ef315d4d124bdff1fb424850d845c1582 
Please contact us directly if source code is required.
